format_version = "1.0.0"

[package]
id = "zac/daggerheart"
name = "匕首之心"
version = "0.4.2"
authors = ["ZZZZzzzzac"]
license = "Apache-2.0"
description = "《匕首之心》二元骰插件，从 .dd help 开始使用。"

[package.seal]
min_version = "1.6.1"

[permissions]
network = false
dangerous = false
http_server = false
file_read = []
file_write = []

[contents]
scripts = ["scripts/daggerheart.js"]
templates = ["templates/daggerheart.yaml"]

[store]
readme = "README.md"
